CREATE TABLE DHI_MX_AUX_PAGOS_CNF_GBL(
    ID_PAGOS_GBL_PK NUMBER(10),
    VAL_TP_PAGO    VARCHAR2(4),
    ID_REG_API     VARCHAR2(18),
    VAL_CNL        VARCHAR2(3),
    COD_EMP        VARCHAR2(4),
    COD_PTO_VTA    VARCHAR2(4),
    VAL_MED_ENT    VARCHAR2(6),
    VAL_REF        VARCHAR2(7),
    COD_USU_CAP    VARCHAR2(10),
    COD_USU_SOL    VARCHAR2(10),
    COD_CVE_TRA    VARCHAR2(5),
    COD_CVE_OPER   VARCHAR2(8),
    IMP            NUMBER(13,2),
    TXT_COM        VARCHAR2(120),
    VAL_DIV_ORD    VARCHAR2(4),
    VAL_CTA_ORD    VARCHAR2(35),
    TXT_NOM_ORD    VARCHAR2(140),
    VAL_IP         VARCHAR2(15),
    VAL_BUC_LI     VARCHAR2(20),
    VAL_CTA_REC    VARCHAR2(35),
    TXT_NOM_REC    VARCHAR2(140),
    VAL_RFC_BEN    VARCHAR2(18),
    ID_INT         VARCHAR2(35), ---
    TXT_NOMB_INT   VARCHAR2(70),
    TXT_CIUD_INT   VARCHAR2(30),
    COD_CPAIS_INT  VARCHAR2(4),
    VAL_BIC_INT    VARCHAR2(11),
    COD_CPAIS_REC  VARCHAR2(4),
    VAL_BIC_REC    VARCHAR2(11),
    ID_BAN_REC     VARCHAR2(35), --
    TXT_NOM_INS_REC  VARCHAR2(70),
    TXT_CUID_INS_REC VARCHAR2(30), ---
    VAL_CTA_BCO_REC  VARCHAR2(35),--
    VAL_NUM_CTA_REC  VARCHAR2(35),---
    VAL_TIP_CTA_REC  VARCHAR2(3),
    TXT_NOMB_REC   VARCHAR2(140),
    TXT_CALLE_BEN_REC VARCHAR2(70),
    VAL_NUMB_BEN_REC  VARCHAR2(7),
    VAL_CP_BEN_REC  VARCHAR2(16),---
    TXT_DIR_BEN_REC VARCHAR2(70),
    COD_CVE_DIV_REC VARCHAR2(4),---
    IMP_ABONO   NUMBER(14,2),
    TXT_CIUD_REC  VARCHAR2(35),
    COD_PAIS_REC  VARCHAR2(4),
    TXT_INF_REM   VARCHAR2(140),
    ID_CAN_CAM    VARCHAR2(2),---
    COD_CVE_DES   VARCHAR2(10),
    VAL_TIPO_BEN_REC  VARCHAR2(1),--
    VAL_PROP_TRANS VARCHAR2(3),--
    FCH_REG           DATE,
    VAL_ESTAT     VARCHAR2(4)
) 

ALTER TABLE DHI_MX_AUX_PAGOS_CNF_GBL
    ADD CONSTRAINT PK_DHI_MX_AUX_PAGOS_CNF_GBL
        PRIMARY KEY (ID_PAGOS_GBL_PK)




CREATE TABLE DHI_MX_AUX_RESP_PAGOS_CNF_GBL(
    ID_RESP_PAGOS_GBL_PK NUMBER(10),
    VAL_ID-ARCH   VARCHAR2(8),
    VAL_ID_REG    VARCHAR2(18),
    MSG_RESP  VARCHAR2(30),
    CVE_ESTATUS VARCHAR2(2),
    REFERENCIA_CONTROL_CANAL VARCHAR2(50),
    DESCRIPCION_CVE_ESTATUS  VARCHAR2(255),
    FCH_RESP DATE
)

ALTER TABLE DHI_MX_AUX_RESP_PAGOS_CNF_GBL
    ADD CONSTRAINT PK_DHI_MX_AUX_RESP_PAGOS_CNF_GBL
        PRIMARY KEY (ID_RESP_PAGOS_GBL_PK)



-- CATALOGO DE CLAVES DE TRANSFER
CREATE TABLE DHI_TSF_MX_MAE_CVE_TRANSFER (
    COD_TP_CTA_ORG   NVARCHAR2(3),  
    COD_TP_CTA_DES   NVARCHAR2(3),  
    COD_TP_PAGO      NVARCHAR2(3),  
    COD_MONEDA       NVARCHAR2(3),  
    COD_CONCEPTO     NVARCHAR2(3),  
    COD_CVE_TRANSF   NVARCHAR2(5),  
    COD_CVE_OPER     NVARCHAR2(8),  
    COD_UBI_IBAN     NVARCHAR2(3)   
);
 
CREATE UNIQUE INDEX IDX_DHI_TSF_TRF_CVE_UN_01
    ON DHI_TSF_MX_MAE_CVE_TRANSFER (
        COD_TP_CTA_ORG,
        COD_TP_CTA_DES,
        COD_TP_PAGO,
        COD_MONEDA,
        COD_CONCEPTO,
        COD_UBI_IBAN
    );
 
 
 
-- CATALOGO DE BANCOS
CREATE TABLE DHI_TSF_MX_MAE_BANCOS (
    COD_BANCO_PK       NVARCHAR2(4)   NOT NULL,  
    FLG_GRUPO_BAN      NVARCHAR2(1),            
    TXT_NOM_BANCO      NVARCHAR2(40),           
    TXT_NOM_BANCIF     NVARCHAR2(40),           
    TXT_DOMICILIO      NVARCHAR2(40),           
    COD_CP_POSTAL      NVARCHAR2(6),            
    TXT_NOM_PLAZA      NVARCHAR2(40),           
    TXT_NOM_PLAZA_V    NVARCHAR2(40),           
    COD_PROVINCIA      NVARCHAR2(2),            
    COD_PAIS           NVARCHAR2(3),            
    NUM_TEL_PREFIJO    NVARCHAR2(3),            
    NUM_TELEFONO       NVARCHAR2(7),            
    NUM_TEL_EXT        NVARCHAR2(7),            
    NUM_FAX            NVARCHAR2(9),            
    COD_SWIFT          CHAR(12),               
    FLG_MCSEPA         SMALLINT      NOT NULL, 
    COD_CVE_BAN        NCHAR(5),               
    COD_TP_INTERM      NCHAR(2),               
    NUM_CEC_BN         NCHAR(3),               
    TXT_NOM_BANCOR     NVARCHAR2(60),           
    TXT_NOM_BANLARGO   NVARCHAR2(255),          
    FCH_ALTA           DATE,                   
    FCH_BAJA           DATE,                   
    FCH_ULT_MOD        DATE,                   
    NUM_BANXIC         NCHAR(5),               
    TXT_LOGIN          NVARCHAR2(10),          
    FCH_ULT_ACT        DATE                    
);
 
ALTER TABLE DHI_TSF_MX_MAE_BANCOS
    ADD CONSTRAINT PK_DHI_TSF_MX_MAE_BANCOS
        PRIMARY KEY (COD_BANCO_PK);
 
CREATE INDEX IDX_DHI_TSF_BAN_CVE_CO_01
    ON DHI_TSF_MX_MAE_BANCOS (COD_CVE_BAN);
 