server:
  port: 8080

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: ${SPRING_DATASOURCE_URL}                 # <- sin default local
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:oracle.jdbc.OracleDriver}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.OracleDialect}

  # CORS global (Spring MVC). Pones el/los orígenes en APP_CORS_ALLOWED_ORIGINS
  mvc:
    cors:
      mappings:
        "[/**]":
          allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
          allowed-methods: ${APP_CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
          allowed-headers: ${APP_CORS_ALLOWED_HEADERS:*}
          allow-credentials: ${APP_CORS_ALLOW_CREDENTIALS:true}
          max-age: ${APP_CORS_MAX_AGE:3600}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    probes:
      enabled: true
 
 
