spring:
  datasource:
    url: jdbc:oracle:thin:@172.22.1.92:1521/XEPDB1
    username: system
    password: neverhack2025
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  # ---- Seguridad JWT (listo para producción, pero desactivado ) ----
  #security:
  #  oauth2:
  #    resourceserver:
  #      jwt:
  #        jwk-set-uri: https://auth.santander.com.mx/.yoquese/jwks.json
